In [1]:
#My API Key
API_KEY = 'T3KQ1ZEODCNBNQUL'

In [2]:
#Download CSV file from Alpha Advantage API: https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=MSFT&interval=5min&apikey=demo&datatype=csv
#Microsoft (MSFT) stock data per Alpha Advantage
#Connect to API via CSV file
import csv
import requests

CSV_URL = ('https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=MSFT&interval=5min&apikey=' + API_KEY + '&datatype=csv')

with requests.session() as s:
    download = s.get(CSV_URL)
    
    decoded_content = download.content.decode('utf-8')
    
    cr = csv.reader(decoded_content.splitlines(), delimiter=',')
    my_list = list(cr)
    for row in my_list:
        print(row)

['timestamp', 'open', 'high', 'low', 'close', 'volume']
['2019-03-18 16:00:00', '117.4000', '117.6000', '117.3400', '117.6000', '1751343']
['2019-03-18 15:55:00', '117.4800', '117.5000', '117.4000', '117.4000', '652325']
['2019-03-18 15:50:00', '117.5300', '117.5900', '117.4700', '117.4800', '694226']
['2019-03-18 15:45:00', '117.4350', '117.5500', '117.4150', '117.5325', '555314']
['2019-03-18 15:40:00', '117.4800', '117.5000', '117.4200', '117.4200', '336219']
['2019-03-18 15:35:00', '117.2950', '117.4950', '117.2725', '117.4850', '423694']
['2019-03-18 15:30:00', '117.3400', '117.3700', '117.2800', '117.2900', '247466']
['2019-03-18 15:25:00', '117.4100', '117.4100', '117.3130', '117.3450', '334478']
['2019-03-18 15:20:00', '117.3000', '117.4300', '117.2900', '117.4200', '324199']
['2019-03-18 15:15:00', '117.3253', '117.3800', '117.2500', '117.2950', '308870']
['2019-03-18 15:10:00', '117.2500', '117.3300', '117.2000', '117.3300', '251002']
['2019-03-18 15:05:00', '117.2800', '117.3000', '117.2300', '117.2500', '183140']
['2019-03-18 15:00:00', '117.2200', '117.2800', '117.1800', '117.2800', '197194']
['2019-03-18 14:55:00', '117.1550', '117.2400', '117.1500', '117.2300', '183789']
['2019-03-18 14:50:00', '117.1607', '117.1750', '117.1000', '117.1600', '107391']
['2019-03-18 14:45:00', '117.1249', '117.1690', '117.0800', '117.1600', '168224']
['2019-03-18 14:40:00', '117.0573', '117.1800', '117.0549', '117.1210', '174124']
['2019-03-18 14:35:00', '117.0800', '117.0900', '116.9600', '117.0522', '217913']
['2019-03-18 14:30:00', '117.1100', '117.1200', '117.0600', '117.0736', '148431']
['2019-03-18 14:25:00', '117.0800', '117.1178', '117.0298', '117.1000', '149176']
['2019-03-18 14:20:00', '117.0000', '117.1300', '117.0000', '117.0900', '174657']
['2019-03-18 14:15:00', '116.9950', '117.0556', '116.9900', '117.0000', '123608']
['2019-03-18 14:10:00', '117.0256', '117.0400', '116.9500', '117.0000', '158150']
['2019-03-18 14:05:00', '117.0450', '117.0800', '117.0000', '117.0300', '156884']
['2019-03-18 14:00:00', '117.0066', '117.0500', '117.0000', '117.0500', '631959']
['2019-03-18 13:55:00', '116.9700', '117.0100', '116.9383', '117.0100', '147186']
['2019-03-18 13:50:00', '116.9700', '117.0000', '116.9448', '116.9750', '204610']
['2019-03-18 13:45:00', '116.8900', '116.9900', '116.8900', '116.9700', '102071']
['2019-03-18 13:40:00', '116.8460', '116.9100', '116.8300', '116.8900', '107766']
['2019-03-18 13:35:00', '116.8400', '116.8500', '116.8100', '116.8500', '138831']
['2019-03-18 13:30:00', '116.9350', '116.9500', '116.8300', '116.8468', '119399']
['2019-03-18 13:25:00', '116.8750', '116.9347', '116.8400', '116.9347', '135375']
['2019-03-18 13:20:00', '116.9300', '116.9300', '116.8700', '116.8800', '144661']
['2019-03-18 13:15:00', '116.9300', '116.9900', '116.9300', '116.9400', '225848']
['2019-03-18 13:10:00', '116.9094', '116.9700', '116.8800', '116.9300', '182862']
['2019-03-18 13:05:00', '116.8050', '116.9000', '116.8000', '116.9000', '142311']
['2019-03-18 13:00:00', '116.8600', '116.8900', '116.7600', '116.8100', '161585']
['2019-03-18 12:55:00', '116.7700', '116.8800', '116.7700', '116.8700', '175913']
['2019-03-18 12:50:00', '116.7250', '116.8100', '116.7250', '116.7800', '207408']
['2019-03-18 12:45:00', '116.6100', '116.7387', '116.6100', '116.7300', '198788']
['2019-03-18 12:40:00', '116.4234', '116.6100', '116.4100', '116.6100', '198310']
['2019-03-18 12:35:00', '116.5300', '116.5300', '116.3950', '116.4200', '189375']
['2019-03-18 12:30:00', '116.4300', '116.5500', '116.4050', '116.5350', '253330']
['2019-03-18 12:25:00', '116.3100', '116.4836', '116.2950', '116.4300', '179252']
['2019-03-18 12:20:00', '116.5000', '116.5500', '116.3200', '116.3400', '264034']
['2019-03-18 12:15:00', '116.4200', '116.5300', '116.3900', '116.5100', '139962']
['2019-03-18 12:10:00', '116.4300', '116.5300', '116.3900', '116.4475', '351249']
['2019-03-18 12:05:00', '116.5000', '116.5400', '116.3900', '116.4400', '193072']
['2019-03-18 12:00:00', '116.5450', '116.5900', '116.4600', '116.4900', '190564']
['2019-03-18 11:55:00', '116.6500', '116.6569', '116.4900', '116.5400', '176847']
['2019-03-18 11:50:00', '116.4300', '116.6670', '116.4300', '116.6481', '215964']
['2019-03-18 11:45:00', '116.3600', '116.4800', '116.3150', '116.4400', '287756']
['2019-03-18 11:40:00', '116.2950', '116.3800', '116.2050', '116.3800', '369804']
['2019-03-18 11:35:00', '116.4700', '116.5000', '116.2900', '116.2900', '309890']
['2019-03-18 11:30:00', '116.5000', '116.5500', '116.4100', '116.4751', '259659']
['2019-03-18 11:25:00', '116.7100', '116.7150', '116.4500', '116.4900', '342674']
['2019-03-18 11:20:00', '116.8750', '116.9000', '116.7100', '116.7100', '231873']
['2019-03-18 11:15:00', '116.8100', '116.9600', '116.8100', '116.8700', '225470']
['2019-03-18 11:10:00', '116.8700', '116.8900', '116.7900', '116.8100', '239874']
['2019-03-18 11:05:00', '117.0700', '117.0950', '116.8200', '116.8599', '277444']
['2019-03-18 11:00:00', '117.1300', '117.2000', '117.0600', '117.0900', '245173']
['2019-03-18 10:55:00', '117.0100', '117.2600', '117.0100', '117.1300', '369802']
['2019-03-18 10:50:00', '117.0100', '117.0500', '116.9128', '117.0100', '241545']
['2019-03-18 10:45:00', '116.8800', '117.0300', '116.8800', '117.0050', '223890']
['2019-03-18 10:40:00', '116.9500', '116.9650', '116.8600', '116.8800', '275960']
['2019-03-18 10:35:00', '117.0180', '117.0400', '116.9200', '116.9450', '221033']
['2019-03-18 10:30:00', '116.9600', '117.0900', '116.9600', '117.0100', '221052']
['2019-03-18 10:25:00', '117.0298', '117.0550', '116.9600', '116.9600', '230320']
['2019-03-18 10:20:00', '116.9200', '117.0100', '116.8650', '117.0100', '197805']
['2019-03-18 10:15:00', '116.9200', '117.0000', '116.8550', '116.8885', '313319']
['2019-03-18 10:10:00', '116.9466', '116.9700', '116.8000', '116.9200', '280471']
['2019-03-18 10:05:00', '116.9768', '117.0900', '116.9500', '116.9600', '392787']
['2019-03-18 10:00:00', '116.7900', '116.9800', '116.7200', '116.9500', '266030']
['2019-03-18 09:55:00', '116.9600', '116.9600', '116.7400', '116.7900', '316731']
['2019-03-18 09:50:00', '116.6800', '116.9600', '116.6400', '116.9500', '537052']
['2019-03-18 09:45:00', '116.5300', '116.7000', '116.4600', '116.6830', '293917']
['2019-03-18 09:40:00', '116.6400', '116.6800', '116.4600', '116.5200', '399868']
['2019-03-18 09:35:00', '116.0700', '116.8400', '116.0500', '116.6300', '1192793']
['2019-03-15 16:00:00', '116.1200', '116.2700', '114.6206', '115.9100', '3832330']
['2019-03-15 15:55:00', '116.5000', '116.5000', '116.1000', '116.1100', '981099']
['2019-03-15 15:50:00', '116.6300', '116.6300', '116.4700', '116.5049', '489732']
['2019-03-15 15:45:00', '116.6900', '116.8000', '116.5750', '116.6200', '489352']
['2019-03-15 15:40:00', '116.7400', '116.7554', '116.6600', '116.6850', '265830']
['2019-03-15 15:35:00', '116.7100', '116.7550', '116.6950', '116.7300', '285071']
['2019-03-15 15:30:00', '116.7542', '116.7600', '116.6800', '116.7200', '223641']
['2019-03-15 15:25:00', '116.7000', '116.7700', '116.6750', '116.7500', '204814']
['2019-03-15 15:20:00', '116.6900', '116.7250', '116.6450', '116.7070', '185901']
['2019-03-15 15:15:00', '116.7500', '116.7500', '116.6900', '116.7000', '206421']
['2019-03-15 15:10:00', '116.7600', '116.8100', '116.7300', '116.7417', '140266']
['2019-03-15 15:05:00', '116.8050', '116.8100', '116.7450', '116.7600', '211919']
['2019-03-15 15:00:00', '116.8900', '116.9200', '116.7900', '116.8050', '348322']
['2019-03-15 14:55:00', '116.9237', '116.9400', '116.8500', '116.8900', '127582']
['2019-03-15 14:50:00', '116.9200', '116.9700', '116.9100', '116.9200', '145078']
['2019-03-15 14:45:00', '116.8800', '116.9900', '116.8525', '116.9300', '185850']
['2019-03-15 14:40:00', '116.8700', '116.8800', '116.7900', '116.8750', '202623']
['2019-03-15 14:35:00', '116.8250', '116.9100', '116.8200', '116.8600', '202933']
['2019-03-15 14:30:00', '116.8100', '116.9100', '116.8050', '116.8250', '242562']
['2019-03-15 14:25:00', '116.7900', '116.8200', '116.7500', '116.8200', '250260']
['2019-03-15 14:20:00', '116.7900', '116.8550', '116.7500', '116.8000', '274072']
['2019-03-15 14:15:00', '116.8600', '116.8950', '116.7900', '116.8000', '194645']

In [3]:
#Create dataframe out of list from CSV file
import pandas as pd
MSFT_CSV = pd.DataFrame(my_list[1:],columns = my_list[0])
MSFT_CSV.head()

             timestamp      open      high       low     close   volume
0  2019-03-18 16:00:00  117.4000  117.6000  117.3400  117.6000  1751343
1  2019-03-18 15:55:00  117.4800  117.5000  117.4000  117.4000   652325
2  2019-03-18 15:50:00  117.5300  117.5900  117.4700  117.4800   694226
3  2019-03-18 15:45:00  117.4350  117.5500  117.4150  117.5325   555314
4  2019-03-18 15:40:00  117.4800  117.5000  117.4200  117.4200   336219

In [4]:
#Using a Stock Market API: https://medium.com/@Keithweaver_/using-a-stock-market-api-4ce65b7c67ac
#Connect to API via JSON file
r = requests.get('https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=MSFT&apikey=' + API_KEY)
if (r.status_code == 200):
    MSFT = r.json()
    MSFT_All_Days = MSFT['Time Series (Daily)']
    MSFT_Single_Date = MSFT_All_Days['2019-03-15']
    MSFT_open = float(MSFT_Single_Date['1. open'])
    MSFT_high = float(MSFT_Single_Date['2. high'])
    MSFT_low = float(MSFT_Single_Date['3. low'])
    MSFT_close = float(MSFT_Single_Date['4. close'])
    MSFT_volume = float(MSFT_Single_Date['5. volume'])

In [5]:
#print results for MSFT on 3/15/2019
print(MSFT_Single_Date)

{'1. open': '115.3400', '2. high': '117.2500', '3. low': '114.5900', '4. close': '115.9100', '5. volume': '54630661'}

In [6]:
#print flaot results for MSFT on 3/15/19
print(MSFT_open)
print(MSFT_high)
print(MSFT_low)
print(MSFT_close)
print(MSFT_volume)

115.34
117.25
114.59
115.91
54630661.0

In [7]:
#View json file
MSFT

{'Meta Data': {'1. Information': 'Daily Prices (open, high, low, close) and Volumes',
  '2. Symbol': 'MSFT',
  '3. Last Refreshed': '2019-03-18',
  '4. Output Size': 'Compact',
  '5. Time Zone': 'US/Eastern'},
 'Time Series (Daily)': {'2019-03-18': {'1. open': '116.1700',
   '2. high': '117.6100',
   '3. low': '116.0500',
   '4. close': '117.5700',
   '5. volume': '31096200'},
  '2019-03-15': {'1. open': '115.3400',
   '2. high': '117.2500',
   '3. low': '114.5900',
   '4. close': '115.9100',
   '5. volume': '54630661'},
  '2019-03-14': {'1. open': '114.5400',
   '2. high': '115.2000',
   '3. low': '114.3300',
   '4. close': '114.5900',
   '5. volume': '30763367'},
  '2019-03-13': {'1. open': '114.1300',
   '2. high': '115.0000',
   '3. low': '113.7800',
   '4. close': '114.5000',
   '5. volume': '35513771'},
  '2019-03-12': {'1. open': '112.8200',
   '2. high': '113.9900',
   '3. low': '112.6499',
   '4. close': '113.6200',
   '5. volume': '26132717'},
  '2019-03-11': {'1. open': '110.9900',
   '2. high': '112.9500',
   '3. low': '110.9800',
   '4. close': '112.8300',
   '5. volume': '26491618'},
  '2019-03-08': {'1. open': '109.1600',
   '2. high': '110.7100',
   '3. low': '108.8000',
   '4. close': '110.5100',
   '5. volume': '22818430'},
  '2019-03-07': {'1. open': '111.4000',
   '2. high': '111.5500',
   '3. low': '109.8650',
   '4. close': '110.3900',
   '5. volume': '25338954'},
  '2019-03-06': {'1. open': '111.8700',
   '2. high': '112.6600',
   '3. low': '111.4300',
   '4. close': '111.7500',
   '5. volume': '17686996'},
  '2019-03-05': {'1. open': '112.2500',
   '2. high': '112.3900',
   '3. low': '111.2300',
   '4. close': '111.7000',
   '5. volume': '19538318'},
  '2019-03-04': {'1. open': '113.0200',
   '2. high': '113.2500',
   '3. low': '110.8000',
   '4. close': '112.2600',
   '5. volume': '26608014'},
  '2019-03-01': {'1. open': '112.8900',
   '2. high': '113.0200',
   '3. low': '111.6650',
   '4. close': '112.5300',
   '5. volume': '23501169'},
  '2019-02-28': {'1. open': '112.0400',
   '2. high': '112.8800',
   '3. low': '111.7300',
   '4. close': '112.0300',
   '5. volume': '29083934'},
  '2019-02-27': {'1. open': '111.6900',
   '2. high': '112.3600',
   '3. low': '110.8800',
   '4. close': '112.1700',
   '5. volume': '21487062'},
  '2019-02-26': {'1. open': '111.2600',
   '2. high': '113.2400',
   '3. low': '111.1700',
   '4. close': '112.3600',
   '5. volume': '21536733'},
  '2019-02-25': {'1. open': '111.7600',
   '2. high': '112.1800',
   '3. low': '111.2600',
   '4. close': '111.5900',
   '5. volume': '23750599'},
  '2019-02-22': {'1. open': '110.0500',
   '2. high': '111.2000',
   '3. low': '109.8200',
   '4. close': '110.9700',
   '5. volume': '27763218'},
  '2019-02-21': {'1. open': '106.9000',
   '2. high': '109.4800',
   '3. low': '106.8700',
   '4. close': '109.4100',
   '5. volume': '29063231'},
  '2019-02-20': {'1. open': '107.8600',
   '2. high': '107.9400',
   '3. low': '106.2900',
   '4. close': '107.1500',
   '5. volume': '21607671'},
  '2019-02-19': {'1. open': '107.7900',
   '2. high': '108.6600',
   '3. low': '107.7800',
   '4. close': '108.1700',
   '5. volume': '18038460'},
  '2019-02-15': {'1. open': '107.9100',
   '2. high': '108.3000',
   '3. low': '107.3624',
   '4. close': '108.2200',
   '5. volume': '26606886'},
  '2019-02-14': {'1. open': '106.3100',
   '2. high': '107.2900',
   '3. low': '105.6600',
   '4. close': '106.9000',
   '5. volume': '21784703'},
  '2019-02-13': {'1. open': '107.5000',
   '2. high': '107.7800',
   '3. low': '106.7100',
   '4. close': '106.8100',
   '5. volume': '18394869'},
  '2019-02-12': {'1. open': '106.1400',
   '2. high': '107.1400',
   '3. low': '105.4800',
   '4. close': '106.8900',
   '5. volume': '25056595'},
  '2019-02-11': {'1. open': '106.2000',
   '2. high': '106.5800',
   '3. low': '104.9650',
   '4. close': '105.2500',
   '5. volume': '18914123'},
  '2019-02-08': {'1. open': '104.3900',
   '2. high': '105.7800',
   '3. low': '104.2603',
   '4. close': '105.6700',
   '5. volume': '21461093'},
  '2019-02-07': {'1. open': '105.1850',
   '2. high': '105.5900',
   '3. low': '104.2900',
   '4. close': '105.2700',
   '5. volume': '29760697'},
  '2019-02-06': {'1. open': '107.0000',
   '2. high': '107.0000',
   '3. low': '105.5300',
   '4. close': '106.0300',
   '5. volume': '20609759'},
  '2019-02-05': {'1. open': '106.0600',
   '2. high': '107.2700',
   '3. low': '105.9600',
   '4. close': '107.2200',
   '5. volume': '27325365'},
  '2019-02-04': {'1. open': '102.8700',
   '2. high': '105.8000',
   '3. low': '102.7700',
   '4. close': '105.7400',
   '5. volume': '31315282'},
  '2019-02-01': {'1. open': '103.7750',
   '2. high': '104.0999',
   '3. low': '102.3500',
   '4. close': '102.7800',
   '5. volume': '35535690'},
  '2019-01-31': {'1. open': '103.8000',
   '2. high': '105.2200',
   '3. low': '103.1800',
   '4. close': '104.4300',
   '5. volume': '55636391'},
  '2019-01-30': {'1. open': '104.6200',
   '2. high': '106.3800',
   '3. low': '104.3300',
   '4. close': '106.3800',
   '5. volume': '49471866'},
  '2019-01-29': {'1. open': '104.8800',
   '2. high': '104.9700',
   '3. low': '102.1700',
   '4. close': '102.9400',
   '5. volume': '31490547'},
  '2019-01-28': {'1. open': '106.2600',
   '2. high': '106.4800',
   '3. low': '104.6600',
   '4. close': '105.0800',
   '5. volume': '29476719'},
  '2019-01-25': {'1. open': '107.2400',
   '2. high': '107.8800',
   '3. low': '106.5900',
   '4. close': '107.1700',
   '5. volume': '31218193'},
  '2019-01-24': {'1. open': '106.8600',
   '2. high': '107.0000',
   '3. low': '105.3400',
   '4. close': '106.2000',
   '5. volume': '23164838'},
  '2019-01-23': {'1. open': '106.1200',
   '2. high': '107.0400',
   '3. low': '105.3400',
   '4. close': '106.7100',
   '5. volume': '25874294'},
  '2019-01-22': {'1. open': '106.7500',
   '2. high': '107.1000',
   '3. low': '104.8600',
   '4. close': '105.6800',
   '5. volume': '32371253'},
  '2019-01-18': {'1. open': '107.4600',
   '2. high': '107.9000',
   '3. low': '105.9100',
   '4. close': '107.7100',
   '5. volume': '37427587'},
  '2019-01-17': {'1. open': '105.0000',
   '2. high': '106.6250',
   '3. low': '104.7600',
   '4. close': '106.1200',
   '5. volume': '28393015'},
  '2019-01-16': {'1. open': '105.2600',
   '2. high': '106.2550',
   '3. low': '104.9600',
   '4. close': '105.3800',
   '5. volume': '29853865'},
  '2019-01-15': {'1. open': '102.5100',
   '2. high': '105.0500',
   '3. low': '101.8800',
   '4. close': '105.0100',
   '5. volume': '31587616'},
  '2019-01-14': {'1. open': '101.9000',
   '2. high': '102.8716',
   '3. low': '101.2600',
   '4. close': '102.0500',
   '5. volume': '28437079'},
  '2019-01-11': {'1. open': '103.1900',
   '2. high': '103.4400',
   '3. low': '101.6400',
   '4. close': '102.8000',
   '5. volume': '28314202'},
  '2019-01-10': {'1. open': '103.2200',
   '2. high': '103.7500',
   '3. low': '102.3800',
   '4. close': '103.6000',
   '5. volume': '30067556'},
  '2019-01-09': {'1. open': '103.8600',
   '2. high': '104.8800',
   '3. low': '103.2445',
   '4. close': '104.2700',
   '5. volume': '32280840'},
  '2019-01-08': {'1. open': '103.0400',
   '2. high': '103.9700',
   '3. low': '101.7134',
   '4. close': '102.8000',
   '5. volume': '31514415'},
  '2019-01-07': {'1. open': '101.6400',
   '2. high': '103.2681',
   '3. low': '100.9800',
   '4. close': '102.0600',
   '5. volume': '35656136'},
  '2019-01-04': {'1. open': '99.7200',
   '2. high': '102.5100',
   '3. low': '98.9300',
   '4. close': '101.9300',
   '5. volume': '44060620'},
  '2019-01-03': {'1. open': '100.1000',
   '2. high': '100.1850',
   '3. low': '97.2000',
   '4. close': '97.4000',
   '5. volume': '42578410'},
  '2019-01-02': {'1. open': '99.5500',
   '2. high': '101.7500',
   '3. low': '98.9400',
   '4. close': '101.1200',
   '5. volume': '35329345'},
  '2018-12-31': {'1. open': '101.2900',
   '2. high': '102.4000',
   '3. low': '100.4400',
   '4. close': '101.5700',
   '5. volume': '33173765'},
  '2018-12-28': {'1. open': '102.0900',
   '2. high': '102.4100',
   '3. low': '99.5200',
   '4. close': '100.3900',
   '5. volume': '38169312'},
  '2018-12-27': {'1. open': '99.3000',
   '2. high': '101.1900',
   '3. low': '96.4000',
   '4. close': '101.1800',
   '5. volume': '49498509'},
  '2018-12-26': {'1. open': '95.1400',
   '2. high': '100.6900',
   '3. low': '93.9600',
   '4. close': '100.5600',
   '5. volume': '51634793'},
  '2018-12-24': {'1. open': '97.6800',
   '2. high': '97.9700',
   '3. low': '93.9800',
   '4. close': '94.1300',
   '5. volume': '43935192'},
  '2018-12-21': {'1. open': '101.6300',
   '2. high': '103.0000',
   '3. low': '97.4600',
   '4. close': '98.2300',
   '5. volume': '111242070'},
  '2018-12-20': {'1. open': '103.0500',
   '2. high': '104.3100',
   '3. low': '98.7800',
   '4. close': '101.5100',
   '5. volume': '70334184'},
  '2018-12-19': {'1. open': '103.6500',
   '2. high': '106.8800',
   '3. low': '101.3500',
   '4. close': '103.6900',
   '5. volume': '68198186'},
  '2018-12-18': {'1. open': '103.7500',
   '2. high': '104.5100',
   '3. low': '102.5200',
   '4. close': '103.9700',
   '5. volume': '49319196'},
  '2018-12-17': {'1. open': '105.4100',
   '2. high': '105.8000',
   '3. low': '101.7100',
   '4. close': '102.8900',
   '5. volume': '56957314'},
  '2018-12-14': {'1. open': '108.2500',
   '2. high': '109.2600',
   '3. low': '105.5000',
   '4. close': '106.0300',
   '5. volume': '47043136'},
  '2018-12-13': {'1. open': '109.5800',
   '2. high': '110.8700',
   '3. low': '108.6300',
   '4. close': '109.4500',
   '5. volume': '31333362'},
  '2018-12-12': {'1. open': '110.8900',
   '2. high': '111.2700',
   '3. low': '109.0400',
   '4. close': '109.0800',
   '5. volume': '36183020'},
  '2018-12-11': {'1. open': '109.8000',
   '2. high': '110.9500',
   '3. low': '107.4400',
   '4. close': '108.5900',
   '5. volume': '42381947'},
  '2018-12-10': {'1. open': '104.8000',
   '2. high': '107.9800',
   '3. low': '103.8900',
   '4. close': '107.5900',
   '5. volume': '40801525'},
  '2018-12-07': {'1. open': '108.3800',
   '2. high': '109.4500',
   '3. low': '104.3000',
   '4. close': '104.8200',
   '5. volume': '45044937'},
  '2018-12-06': {'1. open': '105.8200',
   '2. high': '109.2400',
   '3. low': '105.0000',
   '4. close': '109.1900',
   '5. volume': '49107431'},
  '2018-12-04': {'1. open': '111.9400',
   '2. high': '112.6373',
   '3. low': '108.2115',
   '4. close': '108.5200',
   '5. volume': '45196984'},
  '2018-12-03': {'1. open': '113.0000',
   '2. high': '113.4200',
   '3. low': '110.7300',
   '4. close': '112.0900',
   '5. volume': '34732772'},
  '2018-11-30': {'1. open': '110.7000',
   '2. high': '110.9700',
   '3. low': '109.3600',
   '4. close': '110.8900',
   '5. volume': '33665624'},
  '2018-11-29': {'1. open': '110.3300',
   '2. high': '111.1150',
   '3. low': '109.0300',
   '4. close': '110.1900',
   '5. volume': '28123195'},
  '2018-11-28': {'1. open': '107.8900',
   '2. high': '111.3300',
   '3. low': '107.8600',
   '4. close': '111.1200',
   '5. volume': '46788461'},
  '2018-11-27': {'1. open': '106.2700',
   '2. high': '107.3300',
   '3. low': '105.3600',
   '4. close': '107.1400',
   '5. volume': '29124486'},
  '2018-11-26': {'1. open': '104.7900',
   '2. high': '106.6300',
   '3. low': '104.5800',
   '4. close': '106.4700',
   '5. volume': '32336165'},
  '2018-11-23': {'1. open': '102.1700',
   '2. high': '103.8099',
   '3. low': '102.0000',
   '4. close': '103.0700',
   '5. volume': '13823099'},
  '2018-11-21': {'1. open': '103.6000',
   '2. high': '104.4300',
   '3. low': '102.2400',
   '4. close': '103.1100',
   '5. volume': '28130621'},
  '2018-11-20': {'1. open': '101.8000',
   '2. high': '102.9700',
   '3. low': '99.3528',
   '4. close': '101.7100',
   '5. volume': '64052457'},
  '2018-11-19': {'1. open': '108.2700',
   '2. high': '108.5600',
   '3. low': '103.5500',
   '4. close': '104.6200',
   '5. volume': '44773899'},
  '2018-11-16': {'1. open': '107.0800',
   '2. high': '108.8800',
   '3. low': '106.8000',
   '4. close': '108.2900',
   '5. volume': '33502121'},
  '2018-11-15': {'1. open': '104.9900',
   '2. high': '107.8000',
   '3. low': '103.9100',
   '4. close': '107.2800',
   '5. volume': '38505165'},
  '2018-11-14': {'1. open': '108.1000',
   '2. high': '108.2600',
   '3. low': '104.4700',
   '4. close': '104.9700',
   '5. volume': '39495141'},
  '2018-11-13': {'1. open': '107.5500',
   '2. high': '108.7400',
   '3. low': '106.6400',
   '4. close': '106.9400',
   '5. volume': '35374583'},
  '2018-11-12': {'1. open': '109.4200',
   '2. high': '109.9600',
   '3. low': '106.1000',
   '4. close': '106.8700',
   '5. volume': '33621807'},
  '2018-11-09': {'1. open': '110.8500',
   '2. high': '111.4500',
   '3. low': '108.7600',
   '4. close': '109.5700',
   '5. volume': '32039223'},
  '2018-11-08': {'1. open': '111.8000',
   '2. high': '112.2100',
   '3. low': '110.9100',
   '4. close': '111.7500',
   '5. volume': '25644105'},
  '2018-11-07': {'1. open': '109.4400',
   '2. high': '112.2400',
   '3. low': '109.4000',
   '4. close': '111.9600',
   '5. volume': '37901704'},
  '2018-11-06': {'1. open': '107.3800',
   '2. high': '108.8400',
   '3. low': '106.2800',
   '4. close': '107.7200',
   '5. volume': '24340248'},
  '2018-11-05': {'1. open': '106.3700',
   '2. high': '107.7400',
   '3. low': '105.9000',
   '4. close': '107.5100',
   '5. volume': '27922144'},
  '2018-11-02': {'1. open': '106.4800',
   '2. high': '107.3200',
   '3. low': '104.9750',
   '4. close': '106.1600',
   '5. volume': '37680194'},
  '2018-11-01': {'1. open': '107.0500',
   '2. high': '107.3200',
   '3. low': '105.5300',
   '4. close': '105.9200',
   '5. volume': '33384201'},
  '2018-10-31': {'1. open': '105.4350',
   '2. high': '108.1400',
   '3. low': '105.3900',
   '4. close': '106.8100',
   '5. volume': '51062383'},
  '2018-10-30': {'1. open': '103.6600',
   '2. high': '104.3800',
   '3. low': '100.1100',
   '4. close': '103.7300',
   '5. volume': '65350878'},
  '2018-10-29': {'1. open': '108.1050',
   '2. high': '108.7000',
   '3. low': '101.6300',
   '4. close': '103.8500',
   '5. volume': '55162001'},
  '2018-10-26': {'1. open': '105.6900',
   '2. high': '108.7500',
   '3. low': '104.7600',
   '4. close': '106.9600',
   '5. volume': '55523104'},
  '2018-10-25': {'1. open': '106.5500',
   '2. high': '109.2700',
   '3. low': '106.1500',
   '4. close': '108.3000',
   '5. volume': '61646819'},
  '2018-10-24': {'1. open': '108.4100',
   '2. high': '108.4900',
   '3. low': '101.5901',
   '4. close': '102.3200',
   '5. volume': '63897759'},
  '2018-10-23': {'1. open': '107.7700',
   '2. high': '108.9700',
   '3. low': '105.1100',
   '4. close': '108.1000',
   '5. volume': '43770429'},
  '2018-10-22': {'1. open': '109.3200',
   '2. high': '110.5400',
   '3. low': '108.2400',
   '4. close': '109.6300',
   '5. volume': '26545607'}}}

In [8]:
#View all data for MSFT
MSFT_All_Days

{'2019-03-18': {'1. open': '116.1700',
  '2. high': '117.6100',
  '3. low': '116.0500',
  '4. close': '117.5700',
  '5. volume': '31096200'},
 '2019-03-15': {'1. open': '115.3400',
  '2. high': '117.2500',
  '3. low': '114.5900',
  '4. close': '115.9100',
  '5. volume': '54630661'},
 '2019-03-14': {'1. open': '114.5400',
  '2. high': '115.2000',
  '3. low': '114.3300',
  '4. close': '114.5900',
  '5. volume': '30763367'},
 '2019-03-13': {'1. open': '114.1300',
  '2. high': '115.0000',
  '3. low': '113.7800',
  '4. close': '114.5000',
  '5. volume': '35513771'},
 '2019-03-12': {'1. open': '112.8200',
  '2. high': '113.9900',
  '3. low': '112.6499',
  '4. close': '113.6200',
  '5. volume': '26132717'},
 '2019-03-11': {'1. open': '110.9900',
  '2. high': '112.9500',
  '3. low': '110.9800',
  '4. close': '112.8300',
  '5. volume': '26491618'},
 '2019-03-08': {'1. open': '109.1600',
  '2. high': '110.7100',
  '3. low': '108.8000',
  '4. close': '110.5100',
  '5. volume': '22818430'},
 '2019-03-07': {'1. open': '111.4000',
  '2. high': '111.5500',
  '3. low': '109.8650',
  '4. close': '110.3900',
  '5. volume': '25338954'},
 '2019-03-06': {'1. open': '111.8700',
  '2. high': '112.6600',
  '3. low': '111.4300',
  '4. close': '111.7500',
  '5. volume': '17686996'},
 '2019-03-05': {'1. open': '112.2500',
  '2. high': '112.3900',
  '3. low': '111.2300',
  '4. close': '111.7000',
  '5. volume': '19538318'},
 '2019-03-04': {'1. open': '113.0200',
  '2. high': '113.2500',
  '3. low': '110.8000',
  '4. close': '112.2600',
  '5. volume': '26608014'},
 '2019-03-01': {'1. open': '112.8900',
  '2. high': '113.0200',
  '3. low': '111.6650',
  '4. close': '112.5300',
  '5. volume': '23501169'},
 '2019-02-28': {'1. open': '112.0400',
  '2. high': '112.8800',
  '3. low': '111.7300',
  '4. close': '112.0300',
  '5. volume': '29083934'},
 '2019-02-27': {'1. open': '111.6900',
  '2. high': '112.3600',
  '3. low': '110.8800',
  '4. close': '112.1700',
  '5. volume': '21487062'},
 '2019-02-26': {'1. open': '111.2600',
  '2. high': '113.2400',
  '3. low': '111.1700',
  '4. close': '112.3600',
  '5. volume': '21536733'},
 '2019-02-25': {'1. open': '111.7600',
  '2. high': '112.1800',
  '3. low': '111.2600',
  '4. close': '111.5900',
  '5. volume': '23750599'},
 '2019-02-22': {'1. open': '110.0500',
  '2. high': '111.2000',
  '3. low': '109.8200',
  '4. close': '110.9700',
  '5. volume': '27763218'},
 '2019-02-21': {'1. open': '106.9000',
  '2. high': '109.4800',
  '3. low': '106.8700',
  '4. close': '109.4100',
  '5. volume': '29063231'},
 '2019-02-20': {'1. open': '107.8600',
  '2. high': '107.9400',
  '3. low': '106.2900',
  '4. close': '107.1500',
  '5. volume': '21607671'},
 '2019-02-19': {'1. open': '107.7900',
  '2. high': '108.6600',
  '3. low': '107.7800',
  '4. close': '108.1700',
  '5. volume': '18038460'},
 '2019-02-15': {'1. open': '107.9100',
  '2. high': '108.3000',
  '3. low': '107.3624',
  '4. close': '108.2200',
  '5. volume': '26606886'},
 '2019-02-14': {'1. open': '106.3100',
  '2. high': '107.2900',
  '3. low': '105.6600',
  '4. close': '106.9000',
  '5. volume': '21784703'},
 '2019-02-13': {'1. open': '107.5000',
  '2. high': '107.7800',
  '3. low': '106.7100',
  '4. close': '106.8100',
  '5. volume': '18394869'},
 '2019-02-12': {'1. open': '106.1400',
  '2. high': '107.1400',
  '3. low': '105.4800',
  '4. close': '106.8900',
  '5. volume': '25056595'},
 '2019-02-11': {'1. open': '106.2000',
  '2. high': '106.5800',
  '3. low': '104.9650',
  '4. close': '105.2500',
  '5. volume': '18914123'},
 '2019-02-08': {'1. open': '104.3900',
  '2. high': '105.7800',
  '3. low': '104.2603',
  '4. close': '105.6700',
  '5. volume': '21461093'},
 '2019-02-07': {'1. open': '105.1850',
  '2. high': '105.5900',
  '3. low': '104.2900',
  '4. close': '105.2700',
  '5. volume': '29760697'},
 '2019-02-06': {'1. open': '107.0000',
  '2. high': '107.0000',
  '3. low': '105.5300',
  '4. close': '106.0300',
  '5. volume': '20609759'},
 '2019-02-05': {'1. open': '106.0600',
  '2. high': '107.2700',
  '3. low': '105.9600',
  '4. close': '107.2200',
  '5. volume': '27325365'},
 '2019-02-04': {'1. open': '102.8700',
  '2. high': '105.8000',
  '3. low': '102.7700',
  '4. close': '105.7400',
  '5. volume': '31315282'},
 '2019-02-01': {'1. open': '103.7750',
  '2. high': '104.0999',
  '3. low': '102.3500',
  '4. close': '102.7800',
  '5. volume': '35535690'},
 '2019-01-31': {'1. open': '103.8000',
  '2. high': '105.2200',
  '3. low': '103.1800',
  '4. close': '104.4300',
  '5. volume': '55636391'},
 '2019-01-30': {'1. open': '104.6200',
  '2. high': '106.3800',
  '3. low': '104.3300',
  '4. close': '106.3800',
  '5. volume': '49471866'},
 '2019-01-29': {'1. open': '104.8800',
  '2. high': '104.9700',
  '3. low': '102.1700',
  '4. close': '102.9400',
  '5. volume': '31490547'},
 '2019-01-28': {'1. open': '106.2600',
  '2. high': '106.4800',
  '3. low': '104.6600',
  '4. close': '105.0800',
  '5. volume': '29476719'},
 '2019-01-25': {'1. open': '107.2400',
  '2. high': '107.8800',
  '3. low': '106.5900',
  '4. close': '107.1700',
  '5. volume': '31218193'},
 '2019-01-24': {'1. open': '106.8600',
  '2. high': '107.0000',
  '3. low': '105.3400',
  '4. close': '106.2000',
  '5. volume': '23164838'},
 '2019-01-23': {'1. open': '106.1200',
  '2. high': '107.0400',
  '3. low': '105.3400',
  '4. close': '106.7100',
  '5. volume': '25874294'},
 '2019-01-22': {'1. open': '106.7500',
  '2. high': '107.1000',
  '3. low': '104.8600',
  '4. close': '105.6800',
  '5. volume': '32371253'},
 '2019-01-18': {'1. open': '107.4600',
  '2. high': '107.9000',
  '3. low': '105.9100',
  '4. close': '107.7100',
  '5. volume': '37427587'},
 '2019-01-17': {'1. open': '105.0000',
  '2. high': '106.6250',
  '3. low': '104.7600',
  '4. close': '106.1200',
  '5. volume': '28393015'},
 '2019-01-16': {'1. open': '105.2600',
  '2. high': '106.2550',
  '3. low': '104.9600',
  '4. close': '105.3800',
  '5. volume': '29853865'},
 '2019-01-15': {'1. open': '102.5100',
  '2. high': '105.0500',
  '3. low': '101.8800',
  '4. close': '105.0100',
  '5. volume': '31587616'},
 '2019-01-14': {'1. open': '101.9000',
  '2. high': '102.8716',
  '3. low': '101.2600',
  '4. close': '102.0500',
  '5. volume': '28437079'},
 '2019-01-11': {'1. open': '103.1900',
  '2. high': '103.4400',
  '3. low': '101.6400',
  '4. close': '102.8000',
  '5. volume': '28314202'},
 '2019-01-10': {'1. open': '103.2200',
  '2. high': '103.7500',
  '3. low': '102.3800',
  '4. close': '103.6000',
  '5. volume': '30067556'},
 '2019-01-09': {'1. open': '103.8600',
  '2. high': '104.8800',
  '3. low': '103.2445',
  '4. close': '104.2700',
  '5. volume': '32280840'},
 '2019-01-08': {'1. open': '103.0400',
  '2. high': '103.9700',
  '3. low': '101.7134',
  '4. close': '102.8000',
  '5. volume': '31514415'},
 '2019-01-07': {'1. open': '101.6400',
  '2. high': '103.2681',
  '3. low': '100.9800',
  '4. close': '102.0600',
  '5. volume': '35656136'},
 '2019-01-04': {'1. open': '99.7200',
  '2. high': '102.5100',
  '3. low': '98.9300',
  '4. close': '101.9300',
  '5. volume': '44060620'},
 '2019-01-03': {'1. open': '100.1000',
  '2. high': '100.1850',
  '3. low': '97.2000',
  '4. close': '97.4000',
  '5. volume': '42578410'},
 '2019-01-02': {'1. open': '99.5500',
  '2. high': '101.7500',
  '3. low': '98.9400',
  '4. close': '101.1200',
  '5. volume': '35329345'},
 '2018-12-31': {'1. open': '101.2900',
  '2. high': '102.4000',
  '3. low': '100.4400',
  '4. close': '101.5700',
  '5. volume': '33173765'},
 '2018-12-28': {'1. open': '102.0900',
  '2. high': '102.4100',
  '3. low': '99.5200',
  '4. close': '100.3900',
  '5. volume': '38169312'},
 '2018-12-27': {'1. open': '99.3000',
  '2. high': '101.1900',
  '3. low': '96.4000',
  '4. close': '101.1800',
  '5. volume': '49498509'},
 '2018-12-26': {'1. open': '95.1400',
  '2. high': '100.6900',
  '3. low': '93.9600',
  '4. close': '100.5600',
  '5. volume': '51634793'},
 '2018-12-24': {'1. open': '97.6800',
  '2. high': '97.9700',
  '3. low': '93.9800',
  '4. close': '94.1300',
  '5. volume': '43935192'},
 '2018-12-21': {'1. open': '101.6300',
  '2. high': '103.0000',
  '3. low': '97.4600',
  '4. close': '98.2300',
  '5. volume': '111242070'},
 '2018-12-20': {'1. open': '103.0500',
  '2. high': '104.3100',
  '3. low': '98.7800',
  '4. close': '101.5100',
  '5. volume': '70334184'},
 '2018-12-19': {'1. open': '103.6500',
  '2. high': '106.8800',
  '3. low': '101.3500',
  '4. close': '103.6900',
  '5. volume': '68198186'},
 '2018-12-18': {'1. open': '103.7500',
  '2. high': '104.5100',
  '3. low': '102.5200',
  '4. close': '103.9700',
  '5. volume': '49319196'},
 '2018-12-17': {'1. open': '105.4100',
  '2. high': '105.8000',
  '3. low': '101.7100',
  '4. close': '102.8900',
  '5. volume': '56957314'},
 '2018-12-14': {'1. open': '108.2500',
  '2. high': '109.2600',
  '3. low': '105.5000',
  '4. close': '106.0300',
  '5. volume': '47043136'},
 '2018-12-13': {'1. open': '109.5800',
  '2. high': '110.8700',
  '3. low': '108.6300',
  '4. close': '109.4500',
  '5. volume': '31333362'},
 '2018-12-12': {'1. open': '110.8900',
  '2. high': '111.2700',
  '3. low': '109.0400',
  '4. close': '109.0800',
  '5. volume': '36183020'},
 '2018-12-11': {'1. open': '109.8000',
  '2. high': '110.9500',
  '3. low': '107.4400',
  '4. close': '108.5900',
  '5. volume': '42381947'},
 '2018-12-10': {'1. open': '104.8000',
  '2. high': '107.9800',
  '3. low': '103.8900',
  '4. close': '107.5900',
  '5. volume': '40801525'},
 '2018-12-07': {'1. open': '108.3800',
  '2. high': '109.4500',
  '3. low': '104.3000',
  '4. close': '104.8200',
  '5. volume': '45044937'},
 '2018-12-06': {'1. open': '105.8200',
  '2. high': '109.2400',
  '3. low': '105.0000',
  '4. close': '109.1900',
  '5. volume': '49107431'},
 '2018-12-04': {'1. open': '111.9400',
  '2. high': '112.6373',
  '3. low': '108.2115',
  '4. close': '108.5200',
  '5. volume': '45196984'},
 '2018-12-03': {'1. open': '113.0000',
  '2. high': '113.4200',
  '3. low': '110.7300',
  '4. close': '112.0900',
  '5. volume': '34732772'},
 '2018-11-30': {'1. open': '110.7000',
  '2. high': '110.9700',
  '3. low': '109.3600',
  '4. close': '110.8900',
  '5. volume': '33665624'},
 '2018-11-29': {'1. open': '110.3300',
  '2. high': '111.1150',
  '3. low': '109.0300',
  '4. close': '110.1900',
  '5. volume': '28123195'},
 '2018-11-28': {'1. open': '107.8900',
  '2. high': '111.3300',
  '3. low': '107.8600',
  '4. close': '111.1200',
  '5. volume': '46788461'},
 '2018-11-27': {'1. open': '106.2700',
  '2. high': '107.3300',
  '3. low': '105.3600',
  '4. close': '107.1400',
  '5. volume': '29124486'},
 '2018-11-26': {'1. open': '104.7900',
  '2. high': '106.6300',
  '3. low': '104.5800',
  '4. close': '106.4700',
  '5. volume': '32336165'},
 '2018-11-23': {'1. open': '102.1700',
  '2. high': '103.8099',
  '3. low': '102.0000',
  '4. close': '103.0700',
  '5. volume': '13823099'},
 '2018-11-21': {'1. open': '103.6000',
  '2. high': '104.4300',
  '3. low': '102.2400',
  '4. close': '103.1100',
  '5. volume': '28130621'},
 '2018-11-20': {'1. open': '101.8000',
  '2. high': '102.9700',
  '3. low': '99.3528',
  '4. close': '101.7100',
  '5. volume': '64052457'},
 '2018-11-19': {'1. open': '108.2700',
  '2. high': '108.5600',
  '3. low': '103.5500',
  '4. close': '104.6200',
  '5. volume': '44773899'},
 '2018-11-16': {'1. open': '107.0800',
  '2. high': '108.8800',
  '3. low': '106.8000',
  '4. close': '108.2900',
  '5. volume': '33502121'},
 '2018-11-15': {'1. open': '104.9900',
  '2. high': '107.8000',
  '3. low': '103.9100',
  '4. close': '107.2800',
  '5. volume': '38505165'},
 '2018-11-14': {'1. open': '108.1000',
  '2. high': '108.2600',
  '3. low': '104.4700',
  '4. close': '104.9700',
  '5. volume': '39495141'},
 '2018-11-13': {'1. open': '107.5500',
  '2. high': '108.7400',
  '3. low': '106.6400',
  '4. close': '106.9400',
  '5. volume': '35374583'},
 '2018-11-12': {'1. open': '109.4200',
  '2. high': '109.9600',
  '3. low': '106.1000',
  '4. close': '106.8700',
  '5. volume': '33621807'},
 '2018-11-09': {'1. open': '110.8500',
  '2. high': '111.4500',
  '3. low': '108.7600',
  '4. close': '109.5700',
  '5. volume': '32039223'},
 '2018-11-08': {'1. open': '111.8000',
  '2. high': '112.2100',
  '3. low': '110.9100',
  '4. close': '111.7500',
  '5. volume': '25644105'},
 '2018-11-07': {'1. open': '109.4400',
  '2. high': '112.2400',
  '3. low': '109.4000',
  '4. close': '111.9600',
  '5. volume': '37901704'},
 '2018-11-06': {'1. open': '107.3800',
  '2. high': '108.8400',
  '3. low': '106.2800',
  '4. close': '107.7200',
  '5. volume': '24340248'},
 '2018-11-05': {'1. open': '106.3700',
  '2. high': '107.7400',
  '3. low': '105.9000',
  '4. close': '107.5100',
  '5. volume': '27922144'},
 '2018-11-02': {'1. open': '106.4800',
  '2. high': '107.3200',
  '3. low': '104.9750',
  '4. close': '106.1600',
  '5. volume': '37680194'},
 '2018-11-01': {'1. open': '107.0500',
  '2. high': '107.3200',
  '3. low': '105.5300',
  '4. close': '105.9200',
  '5. volume': '33384201'},
 '2018-10-31': {'1. open': '105.4350',
  '2. high': '108.1400',
  '3. low': '105.3900',
  '4. close': '106.8100',
  '5. volume': '51062383'},
 '2018-10-30': {'1. open': '103.6600',
  '2. high': '104.3800',
  '3. low': '100.1100',
  '4. close': '103.7300',
  '5. volume': '65350878'},
 '2018-10-29': {'1. open': '108.1050',
  '2. high': '108.7000',
  '3. low': '101.6300',
  '4. close': '103.8500',
  '5. volume': '55162001'},
 '2018-10-26': {'1. open': '105.6900',
  '2. high': '108.7500',
  '3. low': '104.7600',
  '4. close': '106.9600',
  '5. volume': '55523104'},
 '2018-10-25': {'1. open': '106.5500',
  '2. high': '109.2700',
  '3. low': '106.1500',
  '4. close': '108.3000',
  '5. volume': '61646819'},
 '2018-10-24': {'1. open': '108.4100',
  '2. high': '108.4900',
  '3. low': '101.5901',
  '4. close': '102.3200',
  '5. volume': '63897759'},
 '2018-10-23': {'1. open': '107.7700',
  '2. high': '108.9700',
  '3. low': '105.1100',
  '4. close': '108.1000',
  '5. volume': '43770429'},
 '2018-10-22': {'1. open': '109.3200',
  '2. high': '110.5400',
  '3. low': '108.2400',
  '4. close': '109.6300',
  '5. volume': '26545607'}}

In [9]:
#Create dataframe from JSON file
from pandas.io.json import json_normalize
MSFT_JSON = pd.DataFrame.from_dict(MSFT_All_Days, orient= 'index')
MSFT_JSON.head()

             1. open   2. high    3. low  4. close 5. volume
2018-10-22  109.3200  110.5400  108.2400  109.6300  26545607
2018-10-23  107.7700  108.9700  105.1100  108.1000  43770429
2018-10-24  108.4100  108.4900  101.5901  102.3200  63897759
2018-10-25  106.5500  109.2700  106.1500  108.3000  61646819
2018-10-26  105.6900  108.7500  104.7600  106.9600  55523104